# 15. 예외처리

## 오류의 종류

### 에러(Error)

- 의도치 않게 프로그램이 종료되는 것
- 하드웨어의 잘못된 동작 또는 고장으로 인한 오류 ex) 정전, 배드섹터 등
- **에러가 발생하면 프로그램이 비정상 종료가 된다.**
- 정상 실행 상태로 돌아갈 수 없다.

### 예외(Exception)

- **사용자의 잘못된 조작 또는 개발자의 잘못된 프로그래밍으로 인한 오류**
- 예외가 발생하면 프로그램이 종료된다.
- **단, 예외 처리를 추가하면 정상 실행 상태로 되돌릴 수 있다.**
- **예외 처리의 목적 : 프로그램을 정상 실행 상태로 돌리는 것**

## 예외의 종류

### 일반 예외(컴파일 예외, checked exception)

- 예외 처리 코드가 없다면, 컴파일 예외 발생한다 **(try - catch 문 이용)**
- ex) `byte a = 300;`

### 실행 예외(Runtime-Exception, unchecked exception)

- 예외 처리 코드를 생략하더라도 컴파일이 되는 예외를 말한다.
- ex) NullPointerException, ArrayIndexOutOfBoundException, NumberFormatException 등
- 단, 프로그래머의 경험 혹은 노하우에 따라 예외 처리 코드 작성이 필요하다.

### 예외 클래스

- 예외(exception) 최고 조상 : `Exception` 클래스
- 일반 예외인가? 런타임 예외인가?
    - 구분 짓는 기준 : `RuntimeException` 클래스
    - `RuntimeException` 을 상속 받으면 `RuntimeException` 이 된다.


---

## 실행 예외(Runtime exception)

### ArrayIndexOutOfBoundsException

- 배열에서 인덱스를 초과하여 접근할 때 발생하는 예외이다.

```java
int[] score = new int[5];
// index 0~4
score[5] = 99;

// Then
// Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 5 ~
```

### NullPointerException

- 인스턴스가 없는데 참조하려고 할 때 발생하는 예외이다.

```java
String str = null;
str.equals("값1");

// Then
// Exception in thread "main" java.lang.NullPointerException ~
```

### NumberFormatException

- 문자를 숫자로 바꾸는 메서드에서 숫자로 바꿀 수 없는 문자가 존재할 때 발생하는 예외

|  반환 타입  |          메서드명(매개 변수)          |           설명           |
|:-------:|:-----------------------------:|:----------------------:|
|   int   |  Integer.parseInt(String s)   | 주어진 문자열을 정수로 변환하여 리턴함  |
| double  | Double.parseDouble(String s)  | 주어진 문자열을 실수로 변환하여 리턴함  |

```java
String str1 = "100";
String str2 = "100가";

int a = Integer.parseInt(str1);
int b = Integer.parseInt(str2);

// "100가"는 숫자로 변환할 수 없다.
// Exception in thread "main" java.lang.NumberFormatException: For input string: "100가" ~
```

### ArithmeticException

- 산술적으로 연산이 되지 않을 때 발생하는 예외

```java
int result = 10/0;
System.out.println(result);

// Exception in thread "main" java.lang.ArithmeticException: / by zero
```

### ClassCastException

- 타입 변환이 되지 않을 때 발생하는 예외

```java
class A {}
class B extends A {}
class C extends A {}

public class Ex {
    public static void main(String[] args) {
        A a = new B();
        C c = (C) a;
    }
}

// a가 누구의 인스턴스를 참조하고 있는가? -> B
// Exception in thread "main" java.lang.ClassCastException ~
```

---

## 예외 처리 코드

### try - catch - finally

- 예외 발생 시 **예외 처리 코드를 작성하면, 프로그램의 종료를 막고 정상적으로 실행**을 유지할 수 있도록 처리한다.
    - **일반 예외 : 반드시 작성해야 한다. (컴파일조차 되지 않는다.)**
    - **실행 예외 : 컴파일러가 체크를 해주지 않는다. 하여, 개발자의 경험으로 작성한다.**
- `try` - `catch` - `finally` 구문으로 예외 처리 코드를 작성한다.

```java
try {
  예외 발생 가능 코드
} catch (예외클래스 e) {
  예외 처리
} finally {
  항상 실행
}

/* 
정상 실행 되었을 경우 : try -> finally
예외가 발생한 경우 : try -> catch -> finally
*/
```

- finally 는 선택사항이다. 작성시 예외가 발생하든 하지 않든 무조건 실행된다.

### 다중 catch

- 예외 별로 예외 처리 코드를 다르게 구현하고자 할 때 사용한다.

```java
try {
  ArrayIndexOutOfBoundsException 발생

  NumberFormatException 발생

} catch (ArrayIndexOutOfBoundsException e) {
  예외 처리 1
} catch (NumberFormatException e) {
  예외 처리 2
}
```

- catch 문은 오로지 하나만 실행하고 빠져 나온다.

### catch 구문의 순서

- **다중 catch 구문을 작성할 때, 상위 클래스가 위에 있으면 안 된다. (다형성으로 기인함)**
- Exception을 catch 문의 맨 아래에 작성해야 하는 이유
    - Exception 클래스는 예외의 최상위 클래스이다.
    - 발생 예외는 무조건 Exception 클래스를 상속 받으므로 하위 catch 구문은 절대 실행되지 않는다.
- 틀린 코드

```java
try {
  ArrayIndexOutOfBoundsException 발생

  NumberFormatException 발생

} catch (Exception e) { // 예외의 최고 조상 : Exception
  예외 처리 1
} catch (ArrayIndexOutOfBoundsException e) {
  예외 처리 2
}
```

- 올바른 코드

```java
try {
  ArrayIndexOutOfBoundsException 발생

  다른 Exception 발생

} catch (ArrayIndexOutOfBoundsException e) {
  예외 처리 1
} catch (Exception e) {
  예외 처리 2
}
```

### 멀티(multi) catch 구문

- JDK 1.7부터 하나의 catch 구문에서 복수의 예외를 처리하고자 할 때 사용한다.
- `|` **(파이프, OR 개념)로 연결한다.**

```java
try {
  ArrayIndexOutOfBoundsException 또는 NumberFormatException 발생

  다른 Exception 발생

} catch (ArrayIndexOutOfBoundsException | NumberFormatException e) {
  예외 처리 1
} catch (Exception e) {
  예외 처리 2
}
```

---

## throws vs throw

- `throws` : 예외를 던지는 것 (호출한 곳으로 예외를 떠넘긴다.)
- `throw` : 예외를 발생시키는 것

### 예외 떠넘기기 - throws

- 메서드 선언부 끝에 `throws`를 붙여서 작성한다.
    - **메서드를 호출한 곳에서 예외를 처리하라고 떠넘긴다.**
    - **호출한 곳에서는 반드시 예외처리 코드가 있어야 한다.**

```java
public class Ex {
    public static void main(String[] args) {
        // method()를 호출한 곳
        try {
            method();
        } catch (Exception e) {}
    }
  
    public static void method() throws Exception {
        System.out.println("예외를 던집니다.");
    }
}
```

### 강제로 예외 발생시키기 - throw

- 코드에서 **강제로 예외를 발생**시킨다.

```java
public class Ex {
    public static void main(String[] args) {
        // method()를 호출한 곳
        try {
            method();
        } catch (Exception e) {
            System.out.println(e.getMessage()); // 예외 발생!!!
        }
    }
  
    public static void method() throws Exception {
        System.out.println("예외를 던집니다.");
        throw new Exception("예외 발생!!!");
    }
}
```

- `throw new XXXException(”메시지”)` 예외 발생 코드를 가지고 있으면, **throws 키워드를 선언부에 반드시 기재하거나 자신의 메서드에서 예외처리를 해주어야 한다.** 만약 자신의 메서드에서 예외처리를 하기 싫다면, **호출한 곳에서는 반드시 예외 처리를 해주어야 한다.**



---

## 사용자 정의 예외 클래스 만들기

- **자바 표준 API에서 제공하지 않는 예외는 직접 프로그래밍 해서 만들어야 한다.**
- 응용 어플리케이션 서비스에서 발생하는 예외
    - 슈팅게임에서 비행기가 체력이 다 되어도 터지지 않는 경우
    - 회원 가입 실패
    - 계좌 잔고 부족
    - 계좌 이체 실패 등
- 사용자 정의 예외 클래스 선언 방법

```java
public class NotExistIDException extends Exception {
    public NotExistIDException() {
    }
  
    public NotExistIDException(String message) {
        super(message);
    }
}

/*
순서
1. 클래스 이름에 관례적으로 Exception을 붙여준다.
2. 일반 예외인지, 런타임 예외인지 선택하여 상속받는다.
3. 기본 생성자를 하나 선언한다.
4. 조상(Exception) 생성자를 반드시 호출한다. (발생 이유와 함께)
*/
```

## 예외 정보 얻기

### getMessage()

- 예외를 발생시킬 때 생성자의 매개값으로 사용한 String 값 리턴
- catch 구문에서 활용한다.

```java
catch (NotExistIDException e) {
    System.out.println(e.getMessage());
}
```

### printStackTrace()

- **개발 시에 자주 사용되며, 개발이 끝나고 배포 시 주석처리 또는 제거한다.**
- 예외 발생 코드를 추적하여 그 로그들을 전부 콘솔에 표식한다.
- 개발자 전용이며, 프로그램을 테스트하고 **디버깅할 때 유용**하다.

```java
catch (NotExistIDException e) {
    e.printStackTrace();
}
```